name: Marafi
favicon: null
layout_spectrum: 0.31404566508717835
typography_spectrum: 0.23639252339489758
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.18296239105984569
  lightness: 0.7054815930314362
  saturation: 0.7619453899096698
  rhythmicContrast: 0.834770344896242
purpose: []
